version: '3.6'

services:

  postgres:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - 5432:5432
    environment:    
      - PG_MODE=primary
      - PG_PRIMARY_USER=postgres
      - PG_PRIMARY_PASSWORD=postgres
      - PG_DATABASE=db1
      - PG_USER=user1
      - PG_PASSWORD=user1
      - PG_ROOT_PASSWORD=rootpostgres
    volumes:
      - ./postgres/data:/var/lib/postgres/data

  vault:
    container_name: "vault"
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  consul:
    container_name: "consul"
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
      - ./consul/data:/consul/data

volumes:
  postgres:
